# Generated by Django 4.2.5 on 2023-12-07 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=40, null=True, unique=True)),
                ('age', models.IntegerField(choices=[(18, '청소년(13세 ~ 18세)'), (29, '청년(19세 ~ 29세)'), (64, '중장년(30 ~ 64세)'), (65, '노년(65세 이상 ~)')], default=29)),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], default='F', max_length=1)),
                ('issue_ln', models.IntegerField(choices=[(1, '네'), (0, '아니오')], default=0)),
                ('issue_hp', models.IntegerField(choices=[(1, '네'), (0, '아니오')], default=0)),
                ('issue_vg', models.IntegerField(choices=[(1, '네'), (0, '아니오')], default=0)),
                ('issue_di', models.IntegerField(choices=[(1, '네'), (0, '아니오')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
