# Generated by Django 4.2.5 on 2023-12-07 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATT_FILE_NO_MAIN', models.CharField(blank=True, max_length=150, null=True)),
                ('ATT_FILE_NO_MK', models.CharField(blank=True, max_length=150, null=True)),
                ('HASH_TAG', models.CharField(blank=True, max_length=150, null=True)),
                ('INFO_CAR_x', models.IntegerField(blank=True, null=True)),
                ('INFO_ENG_x', models.IntegerField(blank=True, null=True)),
                ('INFO_FAT_x', models.IntegerField(blank=True, null=True)),
                ('INFO_NA', models.IntegerField(blank=True, null=True)),
                ('INFO_PRO', models.IntegerField(blank=True, null=True)),
                ('INFO_WGT', models.IntegerField(blank=True, null=True)),
                ('MANUAL_IMG01', models.CharField(blank=True, max_length=150, null=True)),
                ('MANUAL_IMG02', models.CharField(blank=True, max_length=150, null=True)),
                ('MANUAL_IMG03', models.CharField(blank=True, max_length=150, null=True)),
                ('MANUAL_IMG04', models.CharField(blank=True, max_length=150, null=True)),
                ('MANUAL_IMG05', models.CharField(blank=True, max_length=150, null=True)),
                ('MANUAL_IMG06', models.CharField(blank=True, max_length=150, null=True)),
                ('MANUAL_IMG07', models.CharField(blank=True, max_length=150, null=True)),
                ('MANUAL_IMG08', models.CharField(blank=True, max_length=150, null=True)),
                ('MANUAL_IMG09', models.CharField(blank=True, max_length=150, null=True)),
                ('MANUAL_IMG10', models.CharField(blank=True, max_length=150, null=True)),
                ('MANUAL_IMG11', models.CharField(blank=True, max_length=150, null=True)),
                ('MANUAL01', models.CharField(blank=True, max_length=300, null=True)),
                ('MANUAL02', models.CharField(blank=True, max_length=300, null=True)),
                ('MANUAL03', models.CharField(blank=True, max_length=300, null=True)),
                ('MANUAL04', models.CharField(blank=True, max_length=300, null=True)),
                ('MANUAL05', models.CharField(blank=True, max_length=300, null=True)),
                ('MANUAL06', models.CharField(blank=True, max_length=300, null=True)),
                ('MANUAL07', models.CharField(blank=True, max_length=300, null=True)),
                ('MANUAL08', models.CharField(blank=True, max_length=300, null=True)),
                ('MANUAL09', models.CharField(blank=True, max_length=300, null=True)),
                ('MANUAL10', models.CharField(blank=True, max_length=300, null=True)),
                ('MANUAL11', models.CharField(blank=True, max_length=300, null=True)),
                ('RCP_NA_TIP', models.CharField(blank=True, max_length=150, null=True)),
                ('RCP_NM', models.CharField(blank=True, max_length=150, null=True)),
                ('RCP_PARTS_DTLS', models.CharField(blank=True, max_length=300, null=True)),
                ('RCP_PAT2', models.CharField(blank=True, max_length=150, null=True)),
                ('RCP_SEQ', models.IntegerField(blank=True, null=True)),
                ('RCP_WAY2', models.CharField(blank=True, max_length=150, null=True)),
                ('LOW_NA', models.IntegerField(blank=True, null=True)),
                ('HIGH_PRO', models.IntegerField(blank=True, null=True)),
                ('VEGAN', models.IntegerField(blank=True, null=True)),
                ('DIETS', models.IntegerField(blank=True, null=True)),
                ('liked_users', models.ManyToManyField(blank=True, related_name='liked_foods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
