# Generated by Django 4.2.7 on 2023-11-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodel',
            name='FOOD_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
