# Generated by Django 4.2.5 on 2023-12-02 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_import', '0002_foodmodel_liked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmodel',
            name='liked_users',
        ),
    ]
