# Generated by Django 4.2.5 on 2023-12-04 03:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('excel_import', '0003_remove_foodmodel_liked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodel',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_foods', to=settings.AUTH_USER_MODEL),
        ),
    ]
