# Generated by Django 4.2.5 on 2023-12-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_import', '0003_remove_foodmodel_liked_users'),
        ('likeapp', '0002_rename_food_like_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='menu',
        ),
        migrations.AddField(
            model_name='like',
            name='liked_foods',
            field=models.ManyToManyField(blank=True, related_name='liked_foods', to='excel_import.foodmodel'),
        ),
    ]
