# Generated by Django 4.2.5 on 2023-12-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likeapp', '0003_remove_like_menu_like_liked_foods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
