# Generated by Django 4.2.5 on 2023-12-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likeapp', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
